# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a220b30e60334c7f62c67e8264a04abc8755c24b785762c01454f2d326ec3a02bb228d6272b30e67ecea3f2bb3739fc7aeb9cddbf82a4a815684b028fc93a22f

test:
  secret_key_base: 09b75a3fbdfd827c3d60ddcc36183552c0c79a40870387b1853b5fde0fa2f6a1f48e9a57ac382d765222ee98d3d0cff188ab1998841b246e1c611edf46506acb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
